#!/usr/bin/env bash

usage() {
  my_name=$(basename $0)
  [ $# -gt 0 ] && echo "$@" >&2
  echo "usage : ${my_name} ROLE_NAME
  creates a ROLE_NAME directory in the current directory, with a dummy role and unit tests embeded" >&2
  exit 1
}

[ $# -ne 1 ] && usage "role name is mandatory"

role_dir=$(pwd)
role_name=$1

readlink_opt="-e"
readlink ${readlink_opt} / >/dev/null 2>&1 || readlink_opt="-f"
role_unit_dir=$(dirname $(readlink ${readlink_opt} $0))

mkdir -p ${role_name}/{tests,tasks}
touch ${role_name}/tasks/main.yml
cp ${role_unit_dir}/tools/bash_unit ${role_name}/tests
[ ! -f ${role_name}/tests/ansible.cfg ] && cp ${role_unit_dir}/tools/ansible.cfg ${role_name}/tests
[ ! -f ${role_name}/tests/tests_${role_name} ] && cp ${role_unit_dir}/tools/tests ${role_name}/tests/tests_${role_name}
cp -r ${role_unit_dir}/lib ${role_name}/tests

[ ! -d ${role_name}/meta ] && mkdir ${role_name}/meta
[ ! -f ${role_name}/meta/main.yml ] && echo "dependencies: []" > ${role_name}/meta/main.yml
